### ISSUE TITLE
Explorer extension

### ISSUE THREAD

**Issue by HackGorithm** [lordmulder/mediainfo-gui#1]
hello,
It's possible add explorer extension /  right click on a file mediainfo option.
thx

**Comment by lordmulder** [comment]
Please try with this:
http://pastie.org/private/prnf3gjf0ovl0zkfq1uisg

Save that as a .reg file, adjust the path to your MediaInfoXP.exe file (remember to use double-backslashes!) and then double-click on it in Windows Explorer. You may need to reboot (or at least logout + login again) to make the changes take effect.

Regards,
MuldeR

**Comment by HackGorithm** [comment]
perfect thx

**Comment by lordmulder** [comment]
Great. I will probably add a "shell integration" option to the GUI.

**Comment by lordmulder** [comment]
Here is a new test version with Explorer integration support:
http://sourceforge.net/projects/muldersoft/files/MediaInfo%20%28CLI%2BGUI%29/Testing/MediaInfo-GUI.2014-01-14.zip/download

Please remember to remove the registry entries you added manually first!

**Comment by HackGorithm** [comment]
thx ,i'm going to test it

**Comment by HackGorithm** [comment]
it's not possible to save this parameter : enable verbose output 
if shell integration is used, this isn't practical

**Comment by lordmulder** [comment]
Yes, the "enable verbose output" is not saved. It's because MediaInfoXP does not yet have a configuration file where it could save such setting. And I don't think we need to save it. You almost certainly won't need "verbose output" most of the time.

**Comment by HackGorithm** [comment]
just an observation , i rarely use this parameter

**Comment by lordmulder** [comment]
I have finished single-instance support today:
http://sourceforge.net/projects/muldersoft/files/MediaInfo%20%28CLI%2BGUI%29/Testing/MediaInfo-GUI.2014-01-16.zip/download

**Comment by HackGorithm** [comment]
perfect, thanks
