### ISSUE TITLE
--Output=HTML dont work

### ISSUE THREAD

**Issue by iznobe** [lordmulder/mediainfo-gui#12]
Hi i had try to open mediainfo-gui in HTML view in my terminal with this command in ubuntu 22.04 LTS , but don't work :
`mediainfo-gui --Output=HTML /absolute/path/to_file` but still open the simple view .

try also with `mediainfo-gui --Output=XML /absolute/path/to_file` , same tnihg : doesn't work .

**Comment by lordmulder** [comment]
**MediainfoXP** is a GUI completely independent from "official" MediaInfo GUI. It is totally unrelated to `mediainfo-gui` in Linux.

MediainfoXP internally calls the CLI version of MediaInfo and presents the output in the GUI.

If you want to pass parameters to MedaInfo directly, then you have to use the CLI program `mediainfo.exe` directly!

Find binaries here:
https://github.com/lordmulder/mediainfo-gui/tree/master/res/bin

Works for me:
```
E:\Source\MediaInfoXP_Qt\res\bin>MediaInfo.x64-sse2.exe --Output=HTML e:\ViDeOz\MTV_Serj.avi
<html>

<head>
<META http-equiv="Content-Type" content="text/html; charset=utf-8" /></head>
<body>
<table width="100%" border="0" cellpadding="1" cellspacing="2" style="border:1px solid Navy">
<tr>
    <td width="150"><h2>General</h2></td>
  </tr>
  <tr>
    <td><i>Complete name :</i></td>
    <td colspan="3">e:\ViDeOz\MTV_Serj.avi</td>
  </tr>
  [...]
```
