### ISSUE TITLE
MediaInfoXP new version?

### ISSUE THREAD

**Issue by ClassicUA** [lordmulder/mediainfo-gui#3]
Hello.

Is there a new version planned?

**Comment by lordmulder** [comment]
Hello,

MediaInfo v18.08 has just been released a few days ago. I will update to the new version soon™.

(I will be on a trip next week, so can't promise a definitive time frame)

Regards
MuldeR

**Comment by ghost** [comment]
Hey @lordmulder, any chance you could bump to 20.03? Let me know if you'd rather have a separate issue. Thanks for your work!

**Comment by lordmulder** [comment]
> Hey @lordmulder, any chance you could bump to 20.03? Let me know if you'd rather have a separate issue. Thanks for your work!

Yes, I'm planning to release a new build soon™.

**Comment by lordmulder** [comment]
New release is up now:
https://github.com/lordmulder/mediainfo-gui/releases/tag/v2.36-1

**Comment by ghost** [comment]
Thanks a bunch!

**Comment by ghost** [comment]
@lordmulder MediaInfo 20.08 was just released: https://github.com/MediaArea/MediaInfo/releases/tag/v20.08

**Comment by lordmulder** [comment]
soon™
