### ISSUE TITLE
[ ASK ] PBCore 2.0 / 1.2 visualization. "elegant" / readable

### ISSUE THREAD

**Issue by VegethB** [lordmulder/mediainfo-gui#4]
Hi, I would like to ask if there is or is possible to add the "nice" view of the PBcore 1.2 or 2.0 profile (better 2.0). Because a GUI that gives output like avinaptic2 / mediainfoXP but with all the details like the real duration time of the video tracks (frames + samples + MS etc.). Thanks in advance.

**Comment by lordmulder** [comment]
This is a GUI for MediaInfo. It just shows the information that MediaInfo itself reports.

If MediaInfo _can_ provide the desired information, e.g. by setting a certain command-line option, then please provide more details.

Otherwise, this would be a feature request for MediaInfo, **not** for any of the various GUIs (including this one).

Regards.

**Comment by VegethB** [comment]
I mean a formatation of the elements displayed in a "clean" way. Example:
![image](https://user-images.githubusercontent.com/17975351/86611852-8df44780-bfaf-11ea-88d1-941bb7214a0e.png)
VS
![image](https://user-images.githubusercontent.com/17975351/86611880-99477300-bfaf-11ea-924f-d8f12bed0dad.png)

**Comment by lordmulder** [comment]
You can have XML output in MediaInfoXP GUI via the option "Preferences" → "Enable XML-style Output".

...if that is what you want 😏 

If you actually want the opposite, then just turn that option _off_. You'll get output "similar" to your second (lower) picture.

(BTW: If you want to work with XML code, it's probably better to use the MediaInfo CLI front-end right way)

**Comment by VegethB** [comment]
> You can have XML output in MediaInfoXP GUI via the option "Preferences" → "Enable XML-style Output".
> 
> ...if that is what you want 😏
> 
> If you actually want the opposite, then just turn that option _off_. You'll get output "similar" to your second (lower) picture.
> 
> (BTW: If you want to work with XML code, it's probably better to use the MediaInfo CLI front-end right way)

No, I mean the opposite, the first screen shows an output that is difficult to read. What he asked for is to have a "clean" output like the default one, even for PBcore2.0 (so see all PBcore data in a kind of table or html view). That's all. However, modders from the torrent scene have told me that on mediainfo> debug> advanced mode the html mode comes out with the same info as PBCore (so you don't need this anymore). Thanks anyway 👍
