### ISSUE TITLE
Feature Request: Show codec infos for multiple videos in sortable table

### ISSUE THREAD

**Issue by pstein** [lordmulder/mediainfo-gui#6]
Assume I drag & drop multiple videos files onto MI.

Unfortunately MI seems to show all the codec information only as text.

I am missing an function which shows the codec infos in a table (similar to the original MI).
This table should be sortable by click onto the column headers.

Can this be added in the next release?

**Comment by lordmulder** [comment]
This GUI uses the MediaInfo CLI program and it shows the output *exactly* as generated by the MediaInfo CLI program.

Only alternative to standard "plain text" format is XML format, which you can enable in the "Preferences" menu.

(In theory the GUI could request XML output from MediaInfo CLI, then _parse_ that XML data and finally convert it into a different form, e.g. tabular, for presentation. But I currently have **no** plans for that, as it would be **_very_** complex)
